// generated by [dll_builder]: Please do not edit this file 
// ------------------------------------------------------
nativeinteger_path=get_absolute_file_path('loader.sce');
link(nativeinteger_path+'libnativeinteger.dll',['nat_gainblk_i32n','nat_gainblk_i16n','nat_gainblk_i8n','nat_summation_i32n','nat_summation_i16n','nat_summation_i8n'],'c');
