// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
misc_load_path = get_absolute_file_path('misc_loader.sce');
libsprintf_link_num = link(misc_load_path + 'Release/SprintfBlockDLL.dll',['sprintf_block'],'c');
