// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
misc_load_path = get_absolute_file_path('misc_loader.sce');
// mchp16 sources for dspic
comp_fun = ['rt_sinus',..
            'rt_square',..
            'rt_step',..
            'rt_randm',..
            'sprintf_block'];
libsprintf_link_num = link(misc_load_path + 'Release/MiscBlockDll.dll',comp_fun,'c');
clear comp_fun misc_load_path;
