// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef ctrl_window_h
#define ctrl_window_h

//#include <iostream>
#include <stdio.h>
#include <stdlib.h>

#ifdef WIN32 
//#include <winsock2.h>
#include <Winsock2.h>
#pragma comment(lib,"ws2_32.lib")
#endif
#define MAX_CHANNELS 15

extern "C"{
#include "scicos/scicos_block4.h"
}

#ifdef UDP_LIB_EXPORTS
#define UDP_LIB_API	__declspec(dllexport) 
#else
#define UDPR_LIB_API	__declspec(dllimport) 
#endif

struct UDPStruct{
	SOCKET sd;
	sockaddr_in addr;
};

#endif
