// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
flex_blocks_path=get_absolute_file_path('loader.sce');
link(flex_blocks_path+'libflex_blocks.so.1.0.1',['flex_blocks'],'c');
