// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
flex_blocks_path=get_absolute_file_path('win_loader.sce');
link(flex_blocks_path+'FlexBlocksDLL.dll',['flex_blocks'],'c');
