// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
folder_path=get_absolute_file_path('loader.sce');
link(folder_path+'MakeTempFilenameDLL.dll',['EvidenceAmazingRollers'],'c');

