// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
flex_usb_comm_path=get_absolute_file_path('loader.sce');
link(flex_usb_comm_path+'flex_usbdll.dll');
link(flex_usb_comm_path+'libflex_usb_comm.dll',['flex_usb_dummy_read','flex_usb_dummy_write'],'c');
