// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
folder_path=get_absolute_file_path('loader.sce');
roller_link_num = link(folder_path+'RollerGui.dll',['EvidenceRollers'],'c');

