// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
smcube_block_path=get_absolute_file_path('loader.sce');
link(smcube_block_path+'libsmcube_block.so.1.0.1',['smcube_block'],'c');
