// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef _flexsim_h_
#define _flexsim_h_

#include <stdio.h>
#include <stdlib.h>

#ifdef WIN32 
#include <Winsock2.h>
#pragma comment(lib,"ws2_32.lib")
#endif
#pragma comment(lib,"LibScilab.lib")

extern "C"{
#include "scicos_block4.h"
}

#ifdef FLEXSIM_LIB_EXPORTS
#define FLEXSIM_LIB_API	__declspec(dllexport) 
#else
#define FLEXSIM_LIB_API	__declspec(dllimport) 
#endif

/*** Definitions ***/
/* This macro should be used to read block inputs 
 * i: is the index to select the line
 * j: is the index to select the element of the i-th line 
 */
#define input(i,j)  ((double *)block->inptr[i])[j]   

/* This macro should be used to write block outputs 
 * i: is the index to select the line
 * j: is the index to select the element of the i-th line 
 */
#define output(i,j)  ((double *)block->outptr[i])[j]

/* This macro should be used to read integer-type parameters */
#define ipar(i) (block->ipar[i])

/* This macro should be used to read integer-type parameters */
#define rpar(i) (block->rpar[i])

/*** Global variables ***/
extern FILE* fusc_flexsim;      /* File to be used for debug purpose */

#endif /* _flexsim_h_ */
