// generated by [dll_builder]: Please do not edit this file 
// ------------------------------------------------------
flexsim_path=get_absolute_file_path('loader.sce');
flexsim_link_num = link(flexsim_path+'libflexsim.dll',['rt_sinus','rt_square','rt_step','rt_randm','rt_adcin','rt_buzzer','rt_gpin','rt_gpout','rt_lcd','rt_led','rt_pwmout','flex_dmb_adc','flex_dmb_button','flex_dmb_buzzer','flex_dmb_dac','flex_dmb_encoder','flex_dmb_gpin','flex_dmb_gpout','flex_dmb_inertial','flex_dmb_lcd','flex_dmb_ldr','flex_dmb_leds','flex_dmb_ntc','flex_dmb_potin','flex_dmb_pwm'],'c');
