/* Code prototype for common use  */
/*     Generated by Code_Generation toolbox of Scicos with 4.4b7 */
/*     date : 5-Mar-2010 */

/* ---- Headers ---- */
#include <memory.h>
#include <machine.h>

int phase;
int * block_error;

/* block_number */
int block_number;

/*----------------------------------------  Lapack messag function */
void C2F(xerbla)(SRNAME,INFO,L)
     char *SRNAME;
     int *INFO;
     long int L;
{}

void set_block_error(int err)
{
*block_error = err;
  return;
}

void get_block_error(int err)
{
  return *block_error;
}

void set_block_number(int kfun)
{
  block_number = kfun;
  return;
}

int get_block_number()
{
  return block_number;
}

int get_phase_simulation()
{
  return phase;
}

void * scicos_malloc(size_t size)
{
  return malloc(size);
}

void scicos_free(void *p)
{
  free(p);
}

void do_cold_restart()
{
  return;
}

void sciprint (char *fmt)
{
  return;
}

