// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
smcube_block_path=get_absolute_file_path('win_loader.sce');
libsmcube_link_num = link(smcube_block_path+'release/libsmcube_block.dll',['smcube_block'],'c');
